### ISSUE TITLE
I love Rock'n'Roll dot/circle missing

### ISSUE THREAD

**Issue by yaph** [henpe/Whitburn#1]
The dot/circle for the [no 1 from 1982](http://www.remixofthecentury.com/1982/1) "I Love Rock 'N Roll" by Joan Jett & The Blackhearts is missing. When you hit the tweet button when this song is played the message only reads '"" by Joan Jett ' it stops before the & which maybe a hint for the error. Otherwise great work!

**Comment by yaph** [comment]
Just noticed that the tweet text is broken for other artists with a & in the name too, e.g. http://www.remixofthecentury.com/1922/2 but the dot shows up for them. So the missing dot for Joan Jett is a different problem.

**Comment by henpe** [comment]
Thanks for the bug report. 
I've fixed the tweet text, so if you try it now it should work.
The missing dot is because for some of the songs in the original dataset there is no Echo Nest data so we can't visualize them in the scatterplot. I would have expected "I Love Rock 'N Roll" to work though so I'll take a look and see if there is some other issue.

**Comment by yaph** [comment]
Thanks for the quick fix and explaining the possibly cause of the missing dot.
